#version 450

layout(push_constant) uniform PushConstants {
    int valuesPerInvocation;
} pushConstants;

layout(std430, binding = 0) buffer WorkingBuffer {
    int[] values;
} workingBuffer;

layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

void main() {
    uint baseIndex = gl_GlobalInvocationID.x * pushConstants.valuesPerInvocation;

    for (uint offset = 0; offset < pushConstants.valuesPerInvocation; offset++) {
        uint index = baseIndex + offset;
        workingBuffer.values[index] = 123456;
    }
}
